from dataclasses import dataclass, field
from typing import Optional

from backend.app.domain.value_objects.financial.rate import Rate
from backend.app.domain.value_objects.financial.money import Money
from backend.app.domain.value_objects.scheduling.lesson_status import LessonStatus
from backend.app.domain.value_objects.scheduling.time_slot import TimeSlot


@dataclass
class LessonOccurrenceEntity:
    """A single materialized lesson on a specific date, projected from a LessonEntity template.

    Occurrences are generated by the ScheduleProjectionService and stored
    so that attendance, invoicing, and calendar views can operate on
    concrete records rather than re-expanding recurrence rules on every read.

    is_rescheduled flags occurrences whose time_slot was manually changed
    from the template after projection.
    """
    occurrence_id: str
    lesson_id: str
    date: str                        # ISO date "YYYY-MM-DD"
    time_slot: TimeSlot
    instructor_id: str
    room_id: str
    status: LessonStatus = field(default_factory=lambda: LessonStatus(LessonStatus.SCHEDULED))
    rate: Optional[Rate] = None
    is_rescheduled: bool = False
    cancelled_reason: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> "LessonOccurrenceEntity":
        raw_rate = d.get("rate")
        return cls(
            occurrence_id=d["occurrence_id"],
            lesson_id=d["lesson_id"],
            date=d["date"],
            time_slot=TimeSlot(
                start_time=d["start_time"],
                end_time=d["end_time"],
            ),
            instructor_id=d["instructor_id"],
            room_id=d["room_id"],
            status=LessonStatus(d.get("status", LessonStatus.SCHEDULED)),
            rate=Rate.one_time(Money.of(raw_rate)) if raw_rate is not None else None,
            is_rescheduled=bool(d.get("is_rescheduled", False)),
            cancelled_reason=d.get("cancelled_reason"),
        )

    def to_dict(self) -> dict:
        return {
            "occurrence_id": self.occurrence_id,
            "lesson_id": self.lesson_id,
            "date": self.date,
            "start_time": self.time_slot.start_time,
            "end_time": self.time_slot.end_time,
            "instructor_id": self.instructor_id,
            "room_id": self.room_id,
            "status": self.status.value,
            "rate": self.rate.amount.amount if self.rate else None,
            "is_rescheduled": self.is_rescheduled,
            "cancelled_reason": self.cancelled_reason,
        }
